---
# metadata for nginx role

galaxy_info:
  author: quit
  description: installs and starts nginx
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
        - "8"

dependencies: []
