---
# role: fluentbit
# ensures repository, installs package and starts service

- name: Install Fluent Bit repository
  ansible.builtin.shell: |
    curl https://packages.fluentbit.io/fluentbit.key | sudo gpg --dearmor -o /etc/pki/rpm-gpg/fluentbit.gpg
    curl https://packages.fluentbit.io/fluentbit.repo -o /etc/yum.repos.d/fluentbit.repo
  args:
    warn: false

- name: Install Fluent Bit package
  ansible.builtin.dnf:
    name: "{{ fluentbit_package }}"
    state: present

- name: Ensure Fluent Bit service is running
  ansible.builtin.service:
    name: "{{ fluentbit_service }}"
    state: started
    enabled: true
