---
# role: node_exporter
# downloads, installs and configures node_exporter

- name: Create node_exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /sbin/nologin
    system: true

- name: Download node exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_url }}"
    dest: /tmp/node_exporter.tar.gz

- name: Extract binary
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true

- name: Move binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/{{ node_exporter_archive_dir }}/node_exporter"
    dest: "{{ node_exporter_install_path }}"
    mode: '0755'
    remote_src: true

- name: Create systemd service file for node_exporter
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User={{ node_exporter_user }}
      ExecStart={{ node_exporter_install_path }}

      [Install]
      WantedBy=default.target

- name: Start node exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
