---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    update_cache: true

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true